version: "3.8"
services:
    db:
        image: postgres
        restart: always
        env_file:
            - .env
        ports:
            - "5432:5432"
        volumes:
            - db:/var/lib/postgresql/data

    bk-tool:
        build: .
        container_name: bk-tool-c
        image: bk-tool-v1
        depends_on:
            - db
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
        extra_hosts:

volumes:
    db:
        driver: local
