version: "3.8"
services:
    bk-tool:
        build: .
        container_name: bk-tool-c
        image: bk-tool-v1
        volumes:
            - .:/app
            - /app/node_modules
        env_file:
            - .env
