// Generated by https://quicktype.io

export interface IMessage {
    messages: Message[];
    warnings: any[];
}

export interface Message {
    id: number;
    useridfrom: number;
    useridto: number;
    subject: null | string;
    text: string;
    fullmessage: string;
    fullmessageformat: number;
    fullmessagehtml: string;
    smallmessage: string;
    notification: number;
    contexturl: string;
    contexturlname: string;
    timecreated: number;
    timeread: number | null;
    usertofullname: string;
    userfromfullname: string;
    customdata: null | string;
    component?: string;
    eventtype?: string;
    iconurl?: string;
}
